# Generated by Django 4.2.7 on 2023-12-07 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppingCart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_accepted', models.CharField(choices=[('aceptado', 'Aceptado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('procesado', 'Procesado'), ('enviado', 'Enviado'), ('completado', 'Completado')], default=None, max_length=20, null=True)),
                ('id_tracking', models.CharField(default=None, max_length=10)),
                ('shipping_cost', models.FloatField(default=10.0)),
                ('precio_total', models.FloatField()),
                ('delivery_option', models.CharField(choices=[('Domicilio', 'Domicilio'), ('Correos', 'Correos')], default='Domicilio', max_length=20)),
                ('items', models.ManyToManyField(related_name='order_items', to='shoppingCart.cartitem')),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='order.review')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
