# Generated by Django 4.2.7 on 2023-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('procesado', 'Procesado'), ('enviado', 'Enviado'), ('completado', 'Completado')], default=None, max_length=20, null=True),
        ),
    ]
