# Generated by Django 4.2.7 on 2023-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('enviado', 'Enviado'), ('completado', 'Completado')], default=None, max_length=20, null=True),
        ),
    ]
