# Generated by Django 4.2.7 on 2023-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_alter_cartitem_user'),
        ('order', '0004_remove_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_items', to='shoppingCart.cartitem'),
        ),
    ]
