# Generated by Django 4.2.7 on 2023-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_products_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
