# Generated by Django 4.2.7 on 2023-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=10.0),
        ),
    ]
