# Generated by Django 4.2.7 on 2023-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('correos', 'Correos')], default='domicilio', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='id_tracking',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='is_accepted',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
