# Generated by Django 4.2.7 on 2023-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_delivery_option_order_id_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Domicilio', 'Domicilio'), ('Correos', 'Correos')], default='Domicilio', max_length=20),
        ),
    ]
