# Generated by Django 4.2.7 on 2023-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
